### ISSUE TITLE
道理我都懂。。就想请教多页之间怎么跳转呢/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by JimmyGuu** [vv13/vue-cli-multipage#2]
*而且在跳转之后匹配当前页面的路由。*
![image](https://user-images.githubusercontent.com/14993893/50804585-996aa200-1329-11e9-9f43-c1b6c7f7e6a5.png)

**Comment by vv13** [comment]
多页间通过a标签跳转；每个入口若存在router请用hash路由，建议只在index入口增加vue-router，因为dev-server会默认将路由信息重写到index入口，即可匹配到相应的路由。
